name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        echo $(find path/to/folder -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum)
        find path/to/folder -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum
        
    

